# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       gemrb

# >> macros
# << macros
%define _orgname org.gemrb
%define _appname gemrb
%define _gamedatadir %{_datadir}/%{_orgname}.%{_appname}

Summary:    Open-source implementation of Bioware’s Infinity Engine.
Version:    0.9.4
Release:    0
Group:      Applications
License:    GPLv2
URL:        https://github.com/gemrb/gemrb
Source0:    %{name}-%{version}.tar.gz
Source1:    GemRB.cfg
Source100:  gemrb.yaml
Source101:  gemrb-rpmlintrc
Patch0:     SDL2_wayland_rotate.patch
Patch1:     SDL2_wayland_rotate_link_wayland.patch
Patch2:     SDL2_debug_messages.patch
BuildRequires:  pkgconfig(sdl2)
BuildRequires:  pkgconfig(SDL2_mixer)
BuildRequires:  pkgconfig(python3)
BuildRequires:  pkgconfig(egl)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(ogg)
BuildRequires:  pkgconfig(openal)
BuildRequires:  pkgconfig(vorbis)
BuildRequires:  pkgconfig(vorbisfile)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake >= 3.25
BuildRequires:  extra-cmake-modules
BuildRequires:  gcc-c++
BuildRequires:  python3-base >= 3.3
BuildRequires:  python3-libs >= 3.3
BuildRequires:  python3-rpm-macros
BuildRequires:  desktop-file-utils

%description
GemRB (Game Engine Made with preRendered Background) is a portable
open-source reimplementation of the Infinity Engine that underpinned Baldur's
Gate, Icewind Dale and Planescape: Torment. It sports a cleaner design, greater
extensibility and several innovations. Would you like to create a game like
Baldur's Gate?

To try it out you either need some of the ORIGINAL game's data or you can
get a tiny sneak peek by running the included trivial game demo.

The original game data has to be installed if you want to see anything but
the included trivial demo. On non-windows systems either copy it over from
a windows install, use a compatible installer, WINE or extract it manually
from the CDs using the unshield tool.

%if "%{?vendor}" == "chum"
PackageName: GemRB Game Engine
Type: other
PackagerName: nephros
Categories:
 - Game
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/nephros/sailfishos-gemrb
Icon: %{url}/raw/master/artwork/gemrb-logo.png
Url:
  Homepage: https://gemrb.org/
  Help: https://gemrb.org/Documentation.html
  Bugtracker: %{url}/issues
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# SDL2_wayland_rotate.patch
%patch0 -p1
# SDL2_wayland_rotate_link_wayland.patch
%patch1 -p1
# SDL2_debug_messages.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -B%{_builddir}/_build \
    -DSDL_BACKEND=SDL2 \
    -DLIB_DIR=%{_libexecdir}/%{name} \
    -DPLUGIN_DIR=%{_gamedatadir}/plugins/ \
    -DDATA_DIR=%{_gamedatadir} \
    -DSYSCONF_DIR=%{_gamedatadir}/config/ \
    -DICON_DIR=%{_datadir}/icons/hicolor/64x64/apps \
    -DUSE_LIBVLC=OFF \
    CFLAGS="${CFLAGS} -DSDL_RESOLUTION_INDEPENDANCE"


# >> build post
pushd %{_builddir}/_build
%make_build
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
pushd %{_builddir}/_build
%make_install
popd
rm -rf %{buildroot}/%{_docdir}
rm -rf %{buildroot}/%{_mandir}
rm -rf %{buildroot}/%{_datadir}/pixmaps/%{name}.png

install -d %{buildroot}/%{_gamedatadir}/config/
install -D -m644 %SOURCE1 %{buildroot}/%{_gamedatadir}/config/GemRB.cfg
sed -i "s#@@INSTALLDIR@@#%{_gamedatadir}#g" %{buildroot}/%{_gamedatadir}/config/GemRB.cfg
sed -i "s#@@ORGNAME@@#%{_orgname}#g" %{buildroot}/%{_gamedatadir}/config/GemRB.cfg
sed -i "s#@@APPNAME@@#%{_appname}#g" %{buildroot}/%{_gamedatadir}/config/GemRB.cfg

install -d %{buildroot}%{_datadir}/applications
install -D -m644 platforms/linux/gemrb.desktop %{buildroot}%{_datadir}/applications/%{_orgname}.%{_appname}.desktop

desktop-file-edit \
--set-key=Exec --set-value="/usr/bin/gemrb" \
--set-key=Terminal --set-value=false \
--set-key=X-Nemo-Applicaton-Type --set-value=no-invoker \
--set-icon=gemrb \
%{buildroot}%{_datadir}/applications/%{_orgname}.%{_appname}.desktop

cat << EOF >> %{buildroot}%{_datadir}/applications/%{_orgname}.%{_appname}.desktop
[X-Sailjail]
Permissions=Documents;Downloads;Audio
OrganizationName=%{_orgname}
ApplicationName=%{_appname}
EOF

# fix python shebang so we don't depend on python2:
sed -i '1s=^#!/usr/bin/\(python\|env python\)[23]\?=#!%{__python3}=' %{buildroot}%{_bindir}/extend2da.py
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/*
%{_datadir}/applications/%{_orgname}.%{_appname}.desktop
%{_datadir}/icons/*/scalable/apps/%{name}.svg
%{_datadir}/icons/*/*/apps/*.png
%{_libexecdir}/%{name}/
%{_gamedatadir}/
%exclude %{_datadir}/metainfo/*.xml
%exclude %{_datadir}/metainfo
# >> files
# << files
